spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/movie
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f068e6cff10ce83810e8a1db0880aa26
            redirect-uri: "http://localhost:8080/auth/kakao/callback"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: profile_nickname, profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

file:
  dir: C:/Users/HEAD/study/file/